### ISSUE TITLE
Red emoji in the list of greens

### ISSUE THREAD

**Issue by trevorshannon** [CharlieDek/chordle#1]
On my device (Android 12 running Chrome) the yoyo emoji is red instead of green.

![Screenshot_20221205-193138](https://user-images.githubusercontent.com/4656936/205806956-83b265e0-16bb-44eb-8b50-236181d41991.png)

**Comment by CharlieDek** [comment]
In the newest iteration the yellow/green/black colors have been totally ignored in favor of themes.
